GET http://localhost:3000/gallery

###
GET http://localhost:3000/gallery/5ee97ecd50aec85c5c9f3e39

###
POST http://localhost:3000/gallery
Content-Type: application/json

{
    "title": "test art 3",
    "category": "test category",
    "description": "test description 3",
    "imageLocation": "test 3"
}

###
PATCH http://localhost:3000/gallery/5ee97bcf471a8b656876e959
Content-Type: application/json

{
    "title": "test art New"
}

###
DELETE http://localhost:3000/gallery/5ee982de16f08c1d808c9e9c

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}